name: zep_poker0
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter_svg: ^2.0.7  
  flutter_reorderable_list: ^1.3.1
  flutter_draggable_gridview: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

module:
    androidX: true
    androidPackage: com.example.madjong0
    iosBundleIdentifier: com.example.madjong0
